### ISSUE TITLE
Free software license

### ISSUE THREAD

**Issue by nfitzen** [gamescomputersplay/monopoly#1]
Would it be possible to add a [free software] license to the code, such as [`GPL-3.0-or-later`]?
(See also [the GNU Project's license recommendations][recs] and FSFE's [REUSE](https://reuse.software/).)

[recs]: https://www.gnu.org/licenses/license-recommendations.html\

[`GPL-3.0-or-later`]: https://spdx.org/licenses/GPL-3.0-or-later.html "GNU General Public License v3.0 or later"
[free software]: https://www.gnu.org/philosophy/free-sw.html

**Comment by gamescomputersplay** [comment]
Sure. I mean I kinda implied it is free, but let's make it official :)
License added.

**Comment by nfitzen** [comment]
> Sure. I mean I kinda implied it is free, but let's make it official :)

@gamescomputersplay under the copyright law of most countries, it can't be [free (libre)][free software] unless you add a license. Nowhere is this "implied," sadly. If you intend to allow people to modify and fork the program, you should add a license to it.

If you're having trouble choosing, I'd recommend seeing the GNU Project's [license recommendations](https://www.gnu.org/licenses/license-recommendations.html). (In general, [copyleft] is preferred.)

[copyleft]: https://www.gnu.org/licenses/copyleft.html
[free software]: https://www.gnu.org/philosophy/free-sw.html
