### ISSUE TITLE
A player can loose twice

### ISSUE THREAD

**Issue by Aramis7609** [gamescomputersplay/monopoly#7]
even three times

**Comment by Aramis7609** [comment]
[README.md](https://github.com/gamescomputersplay/monopoly/files/10258240/README.md)
[monopoly_simulator-V4.zip](https://github.com/gamescomputersplay/monopoly/files/10258274/monopoly_simulator-V4.zip)

**Comment by Aramis7609** [comment]
in order to close this issue and perhaps some other issues

**Comment by VikVelev** [comment]
Can you explain more what do you mean exactly?
Twice in a single game? Players can be in debt for a while if they have some stuff to sale.

**Comment by gamescomputersplay** [comment]
My guess is that when the player just lost (for example by stopping on someone else's property), and then has to pay again (if someone else get "collect X dollars from everybody" card), the loss may be counted twice - is that it?
